### ISSUE TITLE
Done with the quality check. Facing the following issues.!!

### ISSUE THREAD

**Issue by ritikgarg1234** [tadKeys/tabsat#14]
[Issue.txt](https://github.com/tadKeys/tabsat/files/2775267/Issue.txt)

**Comment by tadKeys** [comment]
Hi,

seems like Bismark is failing. Can you please provide me the output of

`head /home/gm-database/Desktop/tabsat-master/tabsat_test_output_tmap/PGM_316D_IonXpress_028_1_NONDIR_tmap/PGM_316D_IonXpress_028_1_trimmed.fastq`

and

`ls -la /home/gm-database/Desktop/tabsat-master/tabsat_test_output_tmap/PGM_316D_IonXpress_028_1_NONDIR_tmap/`

Thanks

**Comment by ritikgarg1234** [comment]
[output_issue.txt](https://github.com/tadKeys/tabsat/files/2778999/output_issue.txt)

This is the output I'm getting.

**Comment by tadKeys** [comment]
Thanks.

1) Did you run "tabsat/reference/prepareReference.sh" before starting tabsat?

2) Could you please send me the output of
/home/gm-database/Desktop/tabsat-master/tabsat_test_output_tmap/PGM_316D_IonXpress_028_1_NONDIR_tmap/bismark.log

Thanks

**Comment by ritikgarg1234** [comment]
Hello,
Thank you for your prompt reply.
1. I did run "tabsat/reference/prepareReference.sh" before starting tabsat.
2. Afterwhich, I tried executing /home/gm-database/Desktop/tabsat-master/tabsat_test_output_tmap/PGM_316D_IonXpress_028_1_NONDIR_tmap/bismark.log and attached herewith (issue3) is the permission error that I get. 
Also, find the bismark log file that was generated in the output folder, while using tabsat.

[bismark.log](https://github.com/tadKeys/tabsat/files/2783223/bismark.log)

[issue3.txt](https://github.com/tadKeys/tabsat/

**Comment by tadKeys** [comment]
Hi,

it seems like that the reference genome was not prepared correctly. Could you please make an `ls -lR` in the `reference` directory and send me the output. 

Also you could try afterwards to remove the `Bisulfite_Genome` folder and rerun the prepare reference script.

Thanks

**Comment by ritikgarg1234** [comment]
Hello,

Please find attached, the output for the above mentioned command (ls -lR).
[issue3 output.txt](https://github.com/tadKeys/tabsat/files/2786541/issue3.output.txt)

 As per your suggestion, I removed the Bisulfite_Genome folder and tried running the prepare reference script, again. But I think the mm10.fasta file is either missing or corrupted.

**Comment by tadKeys** [comment]
Hi,

as far as I can see, the reason for the errors are the *.2bit files. These files need to be extracted before they can be used.

Please see
http://hgdownload.cse.ucsc.edu/goldenPath/mm10/bigZips/ 
and 
http://hgdownload.cse.ucsc.edu/admin/exe/linux.x86_64/

Also the references need to be name *.fasta - not *.fa, please rename if this is the case (mv hg19.fa hg19.fasta)

Thanks

**Comment by ritikgarg1234** [comment]
Hi,
Done with the extraction and preparation of reference genome. Please see the run and let me know if it is alright (reference file prepared.txt). 
[reference file prepared.txt](https://github.com/tadKeys/tabsat/files/2796204/reference.file.prepared.txt)
After this I tried executing ./test_tabsat_tmap.sh command and attached here is the output I am getting.
[tabsat output.txt](https://github.com/tadKeys/tabsat/files/2796207/tabsat.output.txt)
I think some files are still missing.
Please help!!

Thanks.

**Comment by tadKeys** [comment]
Hi,

I think bismark is still failing - could you please send me again the content of:

`/home/gm-database/Desktop/tabsat-master/tabsat_test_output_tmap/PGM_316D_IonXpress_028_1_NONDIR_tmap/bismark.log`

and  `ls -lR` in the `reference` directory?

Thanks

**Comment by ritikgarg1234** [comment]
Hello,
Please find attached, the content of bismark.log file and the output of ls -lR.
Awaiting your response.
[output_bismark_log.txt](https://github.com/tadKeys/tabsat/files/2821788/output_bismark_log.txt)
[output_ls-lR.txt](https://github.com/tadKeys/tabsat/files/2821793/output_ls-lR.txt)
